const API_BASE = window.RAILFORECAST_API || ((location.hostname==='localhost'||location.hostname==='127.0.0.1')?'http://127.0.0.1:5000':'');
let latest={stations:[],train:null,progress:0};
const $=id=>document.getElementById(id);
function api(path){return `${API_BASE}${path}`}
function normalize(v){return String(v||'').trim().toUpperCase().replace(/\bJUNCTION\b|\bJN\b/g,'').replace(/\s+/g,' ')}
function stationIndex(stations,train){const cur=normalize(train?.current_station||train?.currentStation||train?.current_code);let i=stations.findIndex(s=>normalize(s.code)===cur||normalize(s.station)===cur||normalize(s.station).includes(cur)||cur.includes(normalize(s.station)));return i>=0?i:0}
function render(data){const stations=data.forecast||data.station_forecast||data.stations||[];const train=data.train||{};if(!stations.length)throw new Error('The server returned no route stations.');let idx=stationIndex(stations,train);let sectionProgress=Number(train.section_progress??train.sectionProgress??0);if(!Number.isFinite(sectionProgress)||sectionProgress<0||sectionProgress>1)sectionProgress=0;const progress=Math.max(0,Math.min(100,((idx+sectionProgress)/Math.max(1,stations.length-1))*100));latest={stations,train,progress};$('dashboard').hidden=false;$('trainName').textContent=`${train.number||train.train_number||''} ${train.name||train.train_name||''}`.trim()||'Train';$('routeText').textContent=train.route||`${stations[0].station} → ${stations.at(-1).station}`;$('currentStation').textContent=train.current_station||train.currentStation||stations[idx].station;$('nextStation').textContent=`Next: ${train.next_station||train.nextStation||stations[Math.min(idx+1,stations.length-1)].station}`;const d=Number(train.current_delay??train.delay??0);$('currentDelay').textContent=d>0?`+${d.toFixed(1)} min`:'On time';$('updated').textContent=train.updated||train.last_updated||'Latest API update';$('progressText').textContent=`${Math.round(progress)}%`;$('progressStatus').textContent=`${idx+1} of ${stations.length} stations reached / current`;renderNetwork(stations,progress);renderTable(stations,idx);}
function renderNetwork(stations,progress){const path=$('routePath'), layer=$('stationsLayer'), marker=$('trainMarker'), wrap=$('networkWrap');layer.innerHTML='';const len=path.getTotalLength();stations.forEach((s,i)=>{const p=path.getPointAtLength(len*(i/Math.max(1,stations.length-1)));const el=document.createElement('div');el.className='station '+(i<latestCurrentIndex(stations)?'done':i===latestCurrentIndex(stations)?'current':'');el.style.left=`${p.x/10}%`;el.style.top=`${p.y/4.2}%`;el.innerHTML=`<div class="station-dot"></div><div class="station-name">${s.station||s.station_name||'Station'}</div><div class="station-code">${s.code||s.station_code||''}</div>`;layer.appendChild(el)});const target=len*(progress/100);const p=path.getPointAtLength(target);marker.style.left=`${p.x/10}%`;marker.style.top=`${p.y/4.2}%`;$('routeProgressPath').style.strokeDasharray=`${target} ${len}`;$('journeyFill').style.width=`${progress}%`;$('journeyKnob').style.left=`${progress}%`;}
function latestCurrentIndex(stations){return stationIndex(stations,latest.train)}
function renderTable(stations,current){$('forecastRows').innerHTML=stations.map((s,i)=>{const state=i<current?'done':i===current?'current':'';const eta=s.predicted||s.predicted_time||s.eta||'—';const delay=s.delay??s.predicted_delay;return `<tr><td><b>${s.station||s.station_name}</b><br><small>${s.code||s.station_code||''}</small></td><td>${s.scheduled||s.scheduled_time||'—'}</td><td>${eta}</td><td>${delay===undefined||delay===null?'—':`${Number(delay)>0?'+':''}${Number(delay).toFixed(1)} min`}</td><td><span class="tag ${state}">${i<current?'COMPLETED':i===current?'CURRENT':(s.status||'UPCOMING')}</span></td></tr>`}).join('')}
async function load(){const train=$('train').value.trim(),date=$('date').value;$('error').textContent='';if(!train){$('error').textContent='Enter a train number.';return}const btn=$('forecastBtn');btn.disabled=true;btn.textContent='Loading live route…';try{const r=await fetch(api(`/api/forecast?train=${encodeURIComponent(train)}${date?`&date=${encodeURIComponent(date)}`:''}`));const data=await r.json();if(!r.ok||!data.success)throw new Error(data.error||'Unable to load the forecast.');render(data);$('dashboard').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){$('error').textContent=e.message}finally{btn.disabled=false;btn.textContent='Track & predict →'}}
function demo(){const names=['Guntur Jn','Mangalagiri','Vijayawada Jn','Madhira','Khammam','Dornakal Jn','Mahbubabad','Nekonda','Warangal','Kazipet Jn','Ghanpur','Jangaon','Aler','Bhongir','Charlapalli','Secunderabad Jn'];const codes=['GNT','MAG','BZA','MDR','KMT','DKJ','MABD','NKD','WL','KZJ','GNP','ZN','ALER','BG','CHZ','SC'];const stations=names.map((station,i)=>({station,code:codes[i],scheduled:'—',predicted:i>4?`${String(15+Math.floor(i*0.48)).padStart(2,'0')}:${String((35+i*7)%60).padStart(2,'0')}`:'—',delay:i>4?8+i/2:null,status:'UPCOMING'}));render({train:{number:'12705',name:'Guntur–Secunderabad Intercity',current_station:'Khammam',next_station:'Dornakal Jn',delay:20,section_progress:.38},forecast:stations})}
$('forecastBtn').addEventListener('click',load);$('demoBtn').addEventListener('click',demo);$('date').value=new Date().toISOString().slice(0,10);demo();
